# Generated by Django 3.2.5 on 2021-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charity_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
